#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME/dotfiles}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME/dotfiles}/.zprezto/init.zsh"
fi

# Customize to your needs...




# Relink this file to dotfiles/zshrc
eval "$(ln -s -f $HOME/dotfiles/zshrc .zshrc)"
